---

- name: Define templates' name and annotation
  set_fact:
    template_name: "Template-{{ vm_role }}-{{ '%Y%m%d%H%M' | strftime(ansible_date_time.epoch) }}"
    template_annotation: "Template for {{ vm_role }} created on {{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}"

- name: Create Template VM for {{ vm_role }}
  register: new_vm
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs }}"

    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ vmware_folder }}"

    name: "{{ template_name }}"
    annotation: "{{ template_annotation }}"
    template: "{{ vm_template }}"
    hardware: "{{ vm_hardware }}"
    state: poweredon
    customization:
      hostname: "tmpl-{{ vm_role }}"
      password: "Contrail123!"

    networks: "{{ vm_networks }}"

    wait_for_ip_address: yes

- name: Add additional disks
  when: vm_hdd is defined
  script: >
    add_disk_to_vm.py
    --host '{{ vcenter_hostname }}'
    --user '{{ vcenter_user }}'
    --password '{{ vcenter_password }}'
    --uuid "{{ new_vm.instance.hw_product_uuid }}"
    --disk-type '{{ item.type }}'
    --disk-size '{{ item.size }}'
  with_items: "{{ vm_hdd }}"

- name: Reboot VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs }}"

    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ datacenter_name }}/vm/{{ vmware_folder }}"
    name: "{{ template_name }}"
    state: rebootguest

    wait_for_ip_address: yes

- name: Get correct IP address of new {{ vm_role }}
  register: vm
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs }}"

    datacenter: "{{ datacenter_name }}"

    uuid: "{{ new_vm.instance.hw_product_uuid }}"
  retries: 60
  delay: 15
  until: >
      vm.instance.hw_eth0.ipaddresses | ipv4 | reject("match", "169.254.*") | list

- name: Add host to inventory
  add_host:
    name: "{{ vm.instance.hw_name }}"
    ansible_host: "{{ vm.instance.hw_eth0.ipaddresses | ipv4 | first }}"
    groups: "{{ vm_role }}"
